spring:
  datasource:
    url: jdbc:h2:mem:mett_hdr_test;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE
    username: sa
    password:
  sql:
    init:
      mode: always
      schema-locations: classpath:schema-test.sql
  flyway:
    enabled: false
  data:
    redis:
      repositories:
        enabled: false
