CREATE TABLE organizations (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    global_organization_id VARCHAR(64) NOT NULL,
    global_company_id VARCHAR(64) NULL,
    name VARCHAR(255) NOT NULL,
    organization_type VARCHAR(64) NOT NULL,
    description VARCHAR(1000) NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    owner_user_id BIGINT UNSIGNED NOT NULL,
    managed_by_user_id BIGINT UNSIGNED NOT NULL,
    created_by_user_id BIGINT UNSIGNED NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_organizations_global_id (global_organization_id),
    UNIQUE KEY uk_organizations_global_company_id (global_company_id),
    KEY idx_organizations_owner_user_id (owner_user_id),
    KEY idx_organizations_managed_by_user_id (managed_by_user_id),
    KEY idx_organizations_status (status),
    CONSTRAINT fk_organizations_owner_user FOREIGN KEY (owner_user_id) REFERENCES users (id),
    CONSTRAINT fk_organizations_manager_user FOREIGN KEY (managed_by_user_id) REFERENCES users (id),
    CONSTRAINT fk_organizations_creator_user FOREIGN KEY (created_by_user_id) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE organization_members (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    organization_id BIGINT UNSIGNED NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    member_role VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    joined_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    left_at DATETIME(3) NULL,
    created_by_user_id BIGINT UNSIGNED NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_organization_members_org_user (organization_id, user_id),
    KEY idx_organization_members_user_status (user_id, status),
    KEY idx_organization_members_org_role_status (organization_id, member_role, status),
    CONSTRAINT fk_organization_members_org FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT fk_organization_members_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_organization_members_creator FOREIGN KEY (created_by_user_id) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE teams (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    global_team_id VARCHAR(64) NOT NULL,
    organization_id BIGINT UNSIGNED NULL,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(1000) NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    owner_user_id BIGINT UNSIGNED NOT NULL,
    managed_by_user_id BIGINT UNSIGNED NOT NULL,
    created_by_user_id BIGINT UNSIGNED NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_teams_global_id (global_team_id),
    KEY idx_teams_organization_id (organization_id),
    KEY idx_teams_manager_user_id (managed_by_user_id),
    KEY idx_teams_status (status),
    CONSTRAINT fk_teams_organization FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT fk_teams_owner_user FOREIGN KEY (owner_user_id) REFERENCES users (id),
    CONSTRAINT fk_teams_manager_user FOREIGN KEY (managed_by_user_id) REFERENCES users (id),
    CONSTRAINT fk_teams_creator_user FOREIGN KEY (created_by_user_id) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE team_members (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    team_id BIGINT UNSIGNED NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    member_role VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    joined_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    left_at DATETIME(3) NULL,
    created_by_user_id BIGINT UNSIGNED NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_team_members_team_user (team_id, user_id),
    KEY idx_team_members_user_status (user_id, status),
    KEY idx_team_members_team_role_status (team_id, member_role, status),
    CONSTRAINT fk_team_members_team FOREIGN KEY (team_id) REFERENCES teams (id),
    CONSTRAINT fk_team_members_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_team_members_creator FOREIGN KEY (created_by_user_id) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
